- name: drush makefile
  template:
    src: drush.make.yml.j2
    dest: /var/lib/docker/volumes/{{DRUPAL_PROJECT}}_drupal_sites/_data/drush.make.yml
  register: drush_makefile

- name: check drush status to see if we want to force drush make
  raw: "{{DRUSHCMD_NOSTDOUT}} -l http://localhost status --format=json"
  changed_when: false
  register: drush_status

- name: drush make
  raw: "{{DRUSHCMD}} make -y --no-core --working-copy --contrib-destination=all /var/www/html/sites/drush.make.yml"
  when: drush_makefile.changed or drush_status.stdout != ""
