---
# tasks file for bsw2.drupal_site
- name: check drush status
  raw: "{{DRUSHCMD}} -l http://localhost status --format=json"
  register: rtn
- name: drush site-install
  raw: "{{DRUSHCMD}} -y -vv site-install standard --db-url=mysql://{{MYSQL_USER}}:{{MYSQL_PASSWORD}}@db/{{DBNAME}} --account-name={{DRUPAL_USER}} --account-pass={{DRUPAL_PASSWORD}} --account-mail={{DRUPAL_EMAIL}} --site-mail={{DRUPAL_EMAIL}} --site-name={{SITENAME}} --sites-subdir={{SITEDIR}}"
  when: ( rtn.stdout | from_json)['db-hostname'] is not defined or ( rtn.stdout | from_json)['db-hostname'] != "db"
- name: drush makefile
  template:
    src: drush.make.yml.j2
    dest: /var/lib/docker/volumes/{{DRUPAL_PROJECT}}_drupal_sites/_data/drush.make.yml
- name: drush make
  raw: "{{DRUSHCMD}} make -y --no-core --working-copy --contrib-destination=all /var/www/html/sites/drush.make.yml"
